### ISSUE TITLE
broken import?

### ISSUE THREAD

**Issue by rpodgorny** [RubenKelevra/pacman.store#21] opened 2020-06-01 07:01 UTC
hi,

for last two (or so) days, i can't update some of my systems. it seems some haskell packages are missing (while the rest is ok).

```
error: failed retrieving file 'haskell-http-client-0.7.0-2-x86_64.pkg.tar.zst' from 127.0.0.1:8080 : The requested URL returned error: 404
```
...etc. other packages get downloaded fine.

```
wget http://mirror.kku.ac.th/archlinux/community/os/x86_64/haskell-http-client-0.7.0-2-x86_64.pkg.tar.zst
-> OK

wget http://127.0.0.1:8080/ipns/pkg.pacman.store/arch/community/os/x86_64/haskell-http-client-0.7.0-2-x86_64.pkg.tar.zst
-> 404

wget http://ipfs.io/ipns/pkg.pacman.store/arch/community/os/x86_64/haskell-http-client-0.7.0-2-x86_64.pkg.tar.zst
-> 404
```
...so i don't think it's just "my local" problem.

**Comment by RubenKelevra** [comment] 2020-06-01 15:45
No it's not a local issue. I have seen this too, and fixed it for one package. Though it was limited to this one.

I'll replay the last week again as a diff update - this should fix it.

**Comment by RubenKelevra** [comment] 2020-06-02 03:09
I rolled the full diff through, took longer than expected (8 hours).

My hosting provider has had some serious issues with my disk performance on this server, so I need to run an optimizing job. Don't know how long this is going to take, but the performance is AWFUL - so it really needs to run.

Status can be seen [here](https://github.com/RubenKelevra/pacman.store/wiki/Status,-Announcements-&-Maintenance), as soon as the operation continues it should contain a clean mirror.

**Comment by rpodgorny** [comment] 2020-06-02 16:34
ok. will wait and report later.

anyway, this kind of reminds me it may be a good idea to think about how to avoid dependence on single server in the future (to make the ipfs's "distributed web" claim become reality). is there a way to update ipns records from multiple (backup) locations (servers)?

**Comment by RubenKelevra** [comment] 2020-06-04 02:53
@rpodgorny yes and no. You can use the same key, but currently you would have to wait for the old record to expire. See https://github.com/ipfs/go-ipfs/issues/6683

And seeding IPNS with multiple nodes would also be great:
https://github.com/ipfs/go-ipfs/issues/4536

But we're in the beginning. This is still alpha software.

When the first mentioned limitation is fixed, I could run the software on two nodes which can write to the cluster, and it should eventually lead to both nodes publishing the same CID to the same IPNS, at different times.

So if the second node resolves the IPNS and it already got updated, it won't push another update. But if it's different, it will push an update.

Concurrent writing to the cluster is no issue and concurrent publishing of IPNS records neither. :)

**Comment by RubenKelevra** [comment] 2020-06-04 02:57
All issues should be fixed. And the cluster is running as it should.

I will replace the import server with one with SSDs, since the issue is now _better_ but still way below my expectations. I also contacted the support, since this should be an imminent hardware failure.

**Comment by rpodgorny** [comment] 2020-06-05 09:28
confirming it works for me now. thanks!

**Comment by RubenKelevra** [comment] 2020-06-05 20:20
Very well! :)

I'm replacing the main server in the next hours, to fix the speed issues as well. :)

**Closed** 2020-06-05 20:21 UTC
